version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/teams
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mdp
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    command: ["java", "-jar", "app.jar"] # Commande pour démarrer l'application

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: teams
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/teams
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mdp
    depends_on:
      - db
    command: ["mvn", "test"] # Exécution des tests Maven
    volumes:
      - ./target/surefire-reports:/app/target/surefire-reports # Montre les résultats des tests en local

volumes:
  postgres_data:
